# Generated by Django 4.1.7 on 2023-03-26 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('categoria', models.CharField(max_length=50, verbose_name='Categoria')),
                ('cantidad', models.CharField(max_length=50, verbose_name='Categoria')),
            ],
            options={
                'db_table': 'inventario',
            },
        ),
    ]
