# Generated by Django 4.1.7 on 2023-03-26 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
            ],
            options={
                'db_table': 'categoria',
            },
        ),
        migrations.AlterField(
            model_name='inventario',
            name='cantidad',
            field=models.CharField(max_length=50, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.categoria', verbose_name='Categoria'),
        ),
    ]
